name: Auto Grader

on:
  pull_request:
    paths:
      - 'submissions/**'

jobs:
  grade:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install dependencies
        run: pip install pandas scikit-learn

      - name: Run grader
        run: python grader.py

      - name: Commit leaderboard
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "bot@github.com"
          git add leaderboard_data/leaderboard.json
          git commit -m "Update leaderboard" || echo "No changes"
          git push
