name: Auto Grader

on:
  push:
    paths:
      - 'submissions/**'
  workflow_dispatch:

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pandas scikit-learn

      - name: Run grader
        run: python grader.py

      - name: Commit leaderboard
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add leaderboard.json
          git commit -m "Update leaderboard" || echo "No changes"
          git push
